### ISSUE TITLE
App crashes in android 

### ISSUE THREAD

**Issue by chauhan-saurabh** [IvySpace-Dev/react-native-zoom#9]
App crashes when join meeting 

    --------- beginning of crash
2019-07-25 11:21:15.631 13257-13257/com.helajobseeker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.helajobseeker, PID: 13257
    android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x40 color=0xff9e9e9e vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1905)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6912)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

**Comment by chauhan-saurabh** [comment]
@SoHotSoup Can you please check this

**Comment by rananajam1** [comment]
Did you solve this?

**Comment by rananajam1** [comment]
@chauhan-saurabh  did you solve this?
